knp_paginator:
    page_range: 8
    default_options:
        sort_field_name: 'sort'
        sort_direction_name: 'direction'
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
        filtration: '@KnpPaginator/Pagination/filters.html.twig'